- hosts: django
  gather_facts: no
  roles:
  - django-gunicorn

- hosts: gulp
  gather_facts: no
  roles:
  - gulp-static

- hosts: nginx
  gather_facts: no
  roles:
  - role: ansible.nginx-container
    ASSET_PATHS:
    - /tmp/dist
    PROXY: yes
    PROXY_PASS: http://django:8080
    PROXY_LOCATION: "~* /(admin|static)"
